### ISSUE TITLE
库还是很👍的，希望我可以提几点建议

### ISSUE THREAD

**Issue by Ryan0520** [tianliangyihou/LBPhotoBrowser#1]
库还是很👍的，希望我可以提几点建议
1.支持横竖屏
2.支持asset图片
3.长按图片动画展示菜单
4.支持原图
5.有个loading过程
6.查看图片的时候能把状态栏隐藏，并且手势下拉图片返回的时候，上一个界面得显示状态栏
如果把这些都搞定了，那才叫做高仿微信图片浏览~~~

**Comment by tianliangyihou** [comment]
你说的这几个问题 我会在十一期间尽量都给改了，谢谢你宝贵的建议

**Comment by CrazyRedcrownedcrane** [comment]
当给URL数组中添加一个 无法下载的无效图片地址时程序奔溃！

**Comment by tianliangyihou** [comment]
这个是库里面使用了断言导致的
```objc
当传入的数组中的urString 
[NSURL URLWithString:urString] --> nil
就会抛出异常
```
