### ISSUE TITLE
图片容器放在新创建的window上就完美了

### ISSUE THREAD

**Issue by AlmostSir777** [tianliangyihou/LBPhotoBrowser#10]
如果图片容器放在新创建的window上，就不需要处理statusbar的隐藏，直接可以设置window的设置隐藏statusBar，手势返回的体验就perfect了，楼主的写法还是很好的，collectionView写的我都觉得厉害，这样可以处理大量图片都不是问题，例如聊天页面

**Comment by tianliangyihou** [comment]
这个collectionView里面写的东西我感觉有些还需要优化
同时也非常感谢你的建议,我会尝试修改一下  O(∩_∩)O哈哈~

**Comment by tianliangyihou** [comment]
我按你说的把图片容器放在一个新建的window上后 效果很好
非常感谢您的宝贵建议

**Comment by chenliqian** [comment]
我这里是视频跟图片混编的，之前还有个不需要展示图片的数组，这样不展示的就不随便写一个图片到不展示这里占位，不会造成indexpath数组越界。现在取消了这个不展示数组，又得头疼一下了

**Comment by tianliangyihou** [comment]
这个功能 我一直觉得没啥用,所以新版本就给去掉了,需要的话 你可以下载一下老版本
或者你也可以跟我具体描述一下你的需求,我下个版本把视频播放兼容去

**Comment by chenliqian** [comment]
三克油大大的关照，我这里是图片跟视频混编数组传进去，图片可以展示图片，视频这里是用之前老版本的不展示图片数组去隔离掉，不会造成数组越界的问题。用的挺不错的，要是需求的话，还是想问一下，如果长按删除某张图片的话，removeFromSuperview之后就卡死在这里了，希望有一个刷新或者是跳到下一张的操作

**Comment by tianliangyihou** [comment]
我这么理解对吗 就是老版本基本上已经满足你的需求了,然后就是差个浏览时的删除功能
这样 我把之前的老版本添加上这个功能.是不是就没啥问题了

**Comment by chenliqian** [comment]
对我来说已经是足够用了，当然，希望不占用您的宝贵时间 @_@

**Comment by tianliangyihou** [comment]
不好意思,现在才回你,你的删除按钮需要添加在哪? 右上角,还是长按弹出框上. 我到时写完给你上传到github的另一个仓库里哈

**Comment by Geoege-xll** [comment]
你好！看了大大的代码 你把图片容器放在windows上，展示时就需要填写superview参数了吧， 这个你没删除！！ 要是在图片下面添加描述功能更好了
