### ISSUE TITLE
gif 不能播放

### ISSUE THREAD

**Issue by shafujiu** [tianliangyihou/LBPhotoBrowser#15]
gif 不能播放、、SDWebImage 4.3.3

**Comment by tianliangyihou** [comment]
是的 我之前写这个库的时候SD还是4.0.0, SD4.3.3改变了对gif图片的处理方式,所以当时里面的一些判断失效了,需要更判断方法
我一直想着适配来着 最近也没抽出时间. 这次给自己定个目标 这周一定更新上去.

**Comment by tianliangyihou** [comment]
gif播放问题已解决
