### ISSUE TITLE
其实我在使用的过程遇到了几个bug

### ISSUE THREAD

**Issue by ZuoCaiSong** [tianliangyihou/LBPhotoBrowser#18]
1.你好,网上连续九张gif浏览时,因为内存原因,浏览过的某一张图片会被释放,整个界面变黑,
2.另外有时在dismiss图片浏览器时这行代码会有问题
 self.backgroundColor = [UIColor colorWithRed:0 green:0 blue:0 alpha:scalePercent / _zoomScale];
_zoomScale这个变量作为分母有时会为0
3.请教一下,支持gif,为何不考虑使用FLAnimatedImageView ,而是自己鲁?

**Comment by ZuoCaiSong** [comment]
感谢你的开源代码

**Comment by tianliangyihou** [comment]
非常感谢你的建议，bug我会尽快修复的
至于为什么不使用FLAnimatedImageView，因为我一开始读的YYImage的源码，就仿照作者的思路写了一个。另一方面也是不希望这个库以来太多其他的三方库，这样可能牵涉到三方库不同版本的适配

**Comment by ZuoCaiSong** [comment]
你好,今天更新了你的最新版本,发现在进行网络图片浏览时,有一个非常严重的bug,在LBPhotoBrowserView.m文件中的 - (void)scrollViewDidScroll:(UIScrollView *)scrollView {}方法,例如我要长按做图片分享,保存功能,     LBPhotoCollectionViewCell *cell = (LBPhotoCollectionViewCell *)[self.collectionView cellForItemAtIndexPath:[NSIndexPath indexPathForRow:page inSection:0]];
这个cell经常会获取不到,为nil,以至于  #LBPhotoBrowserManager.defaultManager中对应的currentDisplayModel也为空,导致分享保存失败,我QQ号:2404225920,作者方便加一下吗,希望能够更多的向你学习!

**Comment by tianliangyihou** [comment]
我最近在写新的版本 其实都还没有调试好 所以我在readMe里面写了如果需要 去下载release版本
我马上加下你qq

**Comment by tianliangyihou** [comment]
我加过你qq了 希望能尽早帮你解决问题

**Comment by ZuoCaiSong** [comment]
目前使用gif发现一个bug,就是第一次加载进来会动,第二次再点进来,居然就不会动了....
