### ISSUE TITLE
老铁有bug啊

### ISSUE THREAD

**Issue by peter2022Begin** [tianliangyihou/LBPhotoBrowser#19]
demo里的本地图片测试，添加2张图然后删掉第二张，就会崩溃，断点在LBPhotoBrowserView的scrollViewDidScroll里面，原因是self.models只剩一个元素，数组越界了

**Comment by tianliangyihou** [comment]
你用的是哪个版本,还是最新的?

**Comment by tianliangyihou** [comment]
不好意思 有事耽搁了 现在才回复

**Comment by tianliangyihou** [comment]
老铁 bug修复了 更新一下
