### ISSUE TITLE
楼主，可不可以设定不传frame啊，

### ISSUE THREAD

**Issue by AlmostSir777** [tianliangyihou/LBPhotoBrowser#20]
类似聊天页面，有时候子控件获取不到，不需要滚动到当前图片，就让它点击返回的时候做一个alpha=0的动画消失就行了呀，

**Comment by tianliangyihou** [comment]
这个应该是没啥问题的 我今晚帮你看下吧 今早给你解决方案

**Comment by tianliangyihou** [comment]
尽早 😔

**Comment by AlmostSir777** [comment]
嗯嗯，谢谢楼主了，用过几个图片浏览的，都改过源码，楼主这个是最近换的，感觉比以前好用得多，就差聊天页面没替换，

**Comment by tianliangyihou** [comment]
这个我在写最新版的 基本写完了 最近在进行性能测试
 有问题及时反馈 我会尽早改的

**Comment by AlmostSir777** [comment]
好的，

**Comment by tianliangyihou** [comment]
你试试把子控件的frame获取不到的,传入CGRect(0,0,1,1),然后在下面这个block里面添加这些代码
//---> LBPhotoBrowserManager
    __weak LBPhotoBrowserManager *wmgr = LBPhotoBrowserManager.defaultManager;
    [[LBPhotoBrowserManager defaultManager] addPhotoBrowserWillDismissBlock:^{
        UICollectionViewCell *photocell = [wmgr.currentCollectionView visibleCells].firstObject;
        NSValue *oldValue = wmgr.frames[wmgr.currentPage];
        if (CGRectEqualToRect(oldValue.CGRectValue,CGRectMake(0, 0, 1, 1))) {
            UIImageView *imageView = [[photocell valueForKeyPath:@"zoomScrollView"] valueForKeyPath:@"imageView"];
            NSValue *newValue = [NSValue valueWithCGRect:imageView.frame];
            [wmgr.frames replaceObjectAtIndex:wmgr.currentPage withObject:newValue];
            wmgr.imageViewSuperView = [UIApplication sharedApplication].keyWindow;
        }
    }];

**Comment by AlmostSir777** [comment]
好的好的，谢谢楼主

**Comment by AlmostSir777** [comment]
这个方法豁然开朗，我聊天页面的显示已经解决，这个willDissmissBlock很好用，还可以临时改变imageViewSuperView，谢谢楼主
