### ISSUE TITLE
GIF 不能播放吗？SDWebImage 4.0

### ISSUE THREAD

**Issue by shafujiu** [tianliangyihou/LBPhotoBrowser#25]

**Comment by tianliangyihou** [comment]
可以啊 你播放不了吗

**Comment by shafujiu** [comment]
完全播不了，SDWebImage 4.0 之后就给到另外一种方式去播放gif了 FLAnimatedImage，将UIImageView 替换为 FLAnimatedImageView对象就可以了，但是需要看了你的框架，你是已经解析过gif了，我尝试将你最上层的UIImageView 对象继承至 FLAnimatedImageView。最后应该是我们的git 数据解析的根他提供的控件需要的image对象有些差异吧，未能解决。、

**Comment by tianliangyihou** [comment]
我这周看一下，修复一下这个问题

**Comment by shafujiu** [comment]
那就灰常感谢了

**Comment by shafujiu** [comment]
估计是我之前的版本太老了，我把框架替换了一下 现在可以了， 问题可以关闭了，
有个建议，如果可以的话，希望可以用pod的方式导入就更完美了。
