### ISSUE TITLE
- (instancetype)addTitleClickCallbackBlock:(void (^)(UIImage *,NSIndexPath *,NSString *,BOOL ,NSData *))titleClickCallBackBlock

### ISSUE THREAD

**Issue by shafujiu** [tianliangyihou/LBPhotoBrowser#26]
block 里面穿的indexpath 并不是当前页的 容易造成误会

**Comment by shafujiu** [comment]
准确的说应该是 image 这个没有问题，但是我们的indexpath， 如果进行了滑动 这个indexpath 就不在是 当前页的indexpath

**Comment by tianliangyihou** [comment]
这个是这样的 这个NSIndexPath 指的是你选中的当前页的title的indexpath,
如果你要获取当前页的indexpath,取manager.currentPage

**Comment by shafujiu** [comment]
@tianliangyihou 好的 谢谢，有空 咱来优化优化
