### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by cowboyfzl** [tianliangyihou/LBPhotoBrowser#3]
如果我是用CollectionView展示多张图片，fromImageViews这个参数要传imageView的数组，我该如何传递这个参数？我想达到collectionView和点击后的图片同步滚动展示，请指教

**Comment by tianliangyihou** [comment]
你使用collectionview 是因为图片不能一次展示完毕，然后需要滚动吗？

**Comment by tianliangyihou** [comment]
1.2版本我正在进行测试,已经增加了该功能

**Comment by cowboyfzl** [comment]
是的，非常期待这项功能

**Comment by tianliangyihou** [comment]
目前已经支持了 你可以直接下载个demo看看
