### ISSUE TITLE
怎么能点击黑色背景也让这个关闭掉呢

### ISSUE THREAD

**Issue by a515521265** [tianliangyihou/LBPhotoBrowser#6]
怎么能点击黑色背景也让这个关闭掉呢。。。

**Comment by tianliangyihou** [comment]
这个需要给背景View添加个手势
要是你目前比较急的话,你把你目前的版本告诉我,我帮你加上
要是不急的的话 我正在写一个新的版本 做了很多优化和改动 这个我也会加进去 你可以等等新版本V2.0

**Comment by a515521265** [comment]
好哒，多谢大佬。

**Comment by tianliangyihou** [comment]
新版本我已经添加这个功能了
