### ISSUE TITLE
关于设计成单利的疑问？

### ISSUE THREAD

**Issue by HouWan** [tianliangyihou/LBPhotoBrowser#8]
`LBPhotoBrowserManager`我看是单利的，我有点不太理解为什么设计成单利，个人感觉，对于图片的浏览，想看就点开看，看了就关闭，内存释放。单利就不会释放内存了，而您在`dealloc`里释放通知也没多大意义，因为根本不会执行`dealloc`方法的。不知道您设计成单利的初衷是？

**Comment by tianliangyihou** [comment]
最初的版本功能是很简单的,想着不完全单例用户可以使用,也可以不使用.
1 使用单利的话,很多东西只用配置一次,就不用每次都设置了,单利虽然不会释放内存,也占不了太多的内存
2 用来传值,写起来方便
但是这一版 其实也有觉得写成单利有些鸡肋

**Comment by HouWan** [comment]
嗯，单利的确有单利的好处；关于配置一次就不用再配置，我看有设计成单利的， 有使用`plist`文件的，有使用`NSUserDefaults`的，有使用单纯文件进行配置的。各有优缺点吧。

**Comment by tianliangyihou** [comment]
单利: 程序重新启动的话 就会恢复默认设置 
plist文件: 本地化存储,下次启动的话,会受上次结果的影响
